# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:latest

variables:
  NEO4J_AUTH: neo4j/jan95

# Pick zero or more services to be used on all builds.
# Only needed when using a docker container to run your tests in.
# Check out: http://docs.gitlab.com/ce/ci/docker/using_docker_images.html#what-is-service
services:
  - neo4j:latest

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
  - node_modules/

test:
  script:
   - echo 'neo4j' >> /root/.neo4j/known_hosts
   - npm install
   - BOLT_URL='bolt://neo4j' BOLT_PORT=7687 REST_URL='http://neo4j' REST_PORT=7474 npm test
